### ISSUE TITLE
loadImage is not defined in doxel-viewer.js

### ISSUE THREAD

**Issue by emqiongwu** [doxel/doxel-viewer#23]
I followed the installation instruction. But the the viewer page (http://localhost/doxel-viewer/viewer.html) only shows the camera and the play button. Images and point clouds are all missing. Here is the error message from the console:

> Uncaught ReferenceError: loadImage is not defined at doxel-viewer.js:40
>Uncaught TypeError: Cannot set property 'segmentURL' of undefined at config.js:1
>GET http://localhost/images/ajax-loader.gif net::ERR_CONNECTION_REFUSED

**Comment by emqiongwu** [comment]
I figured it out. I downloaded the zip file. I should recursively clone the git. Thank you!

**Comment by emqiongwu** [comment]
Another thing I noticed that needs to be fixed for successfully loading the demo:
The path in the js/thirdparty/config.js needs to be updated to:
`viewer.segmentURL='example'`

**Comment by bugdanov** [comment]
https://github.com/doxel/doxel-viewer/blob/master/js/doxel-viewer.js#L57
