### ISSUE TITLE
No option to reset password

### ISSUE THREAD

**Issue by Sakrecoer** [doxel/doxel-viewer#26]
In the login prompt, there is no apparent way to reset a lost password.

**Comment by luxigo** [comment]
It's a doxel-loopback issue, there is no authentication handling at the doxel-viewer level.

I had to disable password reset some time after an unnoticed change in the way to handle password change requests with the loopback framework (everything else was working fine..)  I will push the patch I made last week as soon as possible (just need to test) . Sorry for the inconvenience.

**Comment by Sakrecoer** [comment]
Thank you for taking the time to look into this! :)
