### ISSUE TITLE
potree buttons

### ISSUE THREAD

**Issue by polto** [doxel/doxel-viewer#7]
potree buttons for measuring are not selectable.

**Comment by bugdanov** [comment]
Maybe because the reference frame was removed in viewer.js
When you press the buttons, navigation controls are frozen (cannot rotate or move)

**Comment by bugdanov** [comment]
Fixed in the new viewer.js on your server.

The original viewer.js file is coming from the PotreeConverter resource directory, it will be added in the PotreeConverter submodule, either for this project or for a project that includes doxel-viewer.
